name: Build and Push Docker image

on:
  push:
    branches:
      - main   # or master, or whichever branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest

    # Optional: Tag with commit SHA and push both tags
    # Uncomment the following lines if you want to tag with the commit SHA as well
    #   - name: Build Docker image
    #     run: |
    #       docker build -t ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest \
    #                    -t ${{ secrets.DOCKER_USERNAME }}/optilogic-web:${{ github.sha }} .
    #   - name: Push Docker image
    #     run: |
    #       docker push ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest
    #       docker push ${{ secrets.DOCKER_USERNAME }}/optilogic-web:${{ github.sha }}



