name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Clean up dangling Docker images (optional but helps avoid build issues)
      - name: Clean up old Docker images
        run: |
          docker image prune -af

      # Step 4: Build and push Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest
            ${{ secrets.DOCKER_USERNAME }}/optilogic-web:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/optilogic-web:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/optilogic-web:cache,mode=max

      # Step 5: Verify the image was pushed (optional)
      - name: Verify Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest
          docker images | grep optilogic-web
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/optilogic-web:latest --version